// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQMg4NdBq_xkAcYlxx8YBZ0xuAvCcX2x8',
    appId: '1:24468653843:web:23a90d94a90a406b1b7ce6',
    messagingSenderId: '24468653843',
    projectId: 'movie-expert-project-final',
    authDomain: 'movie-expert-project-final.firebaseapp.com',
    storageBucket: 'movie-expert-project-final.appspot.com',
    measurementId: 'G-Y475Z5MPVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXwuICVc5CL4iE-bybL4Y_DhtbL9FbwME',
    appId: '1:24468653843:android:15b564528c9f289c1b7ce6',
    messagingSenderId: '24468653843',
    projectId: 'movie-expert-project-final',
    storageBucket: 'movie-expert-project-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgrdwBKdKnKMDcB-Xp_D7qankbn-O5Z6o',
    appId: '1:24468653843:ios:df8538431e7f01f71b7ce6',
    messagingSenderId: '24468653843',
    projectId: 'movie-expert-project-final',
    storageBucket: 'movie-expert-project-final.appspot.com',
    iosClientId: '24468653843-shdtk183nsdhjqmgpg53mohuuf6r9d90.apps.googleusercontent.com',
    iosBundleId: 'com.example.dimovieFinalExpertProject',
  );
}
